services:
  # 1. Managed Redis
  - type: redis
    name: render-redis-cache
    region: oregon
    ipAllowList: []
    plan: free
    maxmemoryPolicy: allkeys-lru

  # 2. Caching API Server
  - type: web
    name: redis-caching-api
    env: docker
    region: oregon
    plan: free
    healthCheckPath: /health
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: render-redis-cache
          property: connectionString
      - key: API_KEY
        generateValue: true
      - key: NODE_ENV
        value: production
